source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!
#ignore all warnings from all pods
inhibit_all_warnings!

target 'NetWorkDemo' do
pod 'MJExtension’
pod 'YTKNetwork’
pod 'FMDB'
pod 'SDWebImage'
pod 'MBProgressHUD'

end
